name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: php -v
      - run: composer -v
      - run: composer install
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" -a -z --delete -r --exclude /.git/ --exclude /.github/ --exclude /.gitignore . dont7panic@dont7panic.ru:/var/www/yii2-study.dont7panic.ru/html/