name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - run: npm ci
      - run: npm run build
      - run: |
          touch .env
          echo YII_DEBUG=${{ secrets.YII_DEBUG }} >> .env
          echo YII_ENV=${{ secrets.YII_ENV }} >> .env
          echo DB_DRIVER=${{ secrets.DB_DRIVER }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no dont7panic@dont7panic.ru 'sudo chmod 777 -R /var/www/'
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --chmod=777 -A -a -z --delete -r --exclude /.git/ --exclude /.github/ --exclude /.gitignore . dont7panic@dont7panic.ru:/var/www/yii2-study.dont7panic.ru/html/
